[package]
name = "liter2"
version = "0.1.0"
authors = ["Mark Sherry <mdsherry@gmail.com>"]

[dependencies]
reqwest = "0.7.1"
scraper = "0.4.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
termion = "1.4.0"
error-chain = "0.10.0"